### ISSUE TITLE
--update flag not correctly updating papers_manifest.yml for license type "Unknown"

### ISSUE THREAD

**Issue by anothermh** [newrelic/papers#20]
If the original `papers_manifest.yml` created with `papers --generate` recorded a license with a type `Unknown`, then running `papers --update` will replace the license value `Unknown` with `License Change! Was 'Unknown', is now [nil]`. It seems like it should stay `Unknown`.

Steps to reproduce in a Rails app:

1. Add `gem "coolline", "~> 0.5.0"` to `Gemfile`
2. `bundle`
3. `rm config/papers_manifest.yml`
4. `papers --generate`
5. Note that license type is `Unknown`
6. `papers --update`
7. Note that license type is `License Change! Was 'Unknown', is now [nil]`

@jasonrclark The problem appears to be here: https://github.com/newrelic/papers/blame/ed65d2feb18d627907c7b9f1be75dbf0da987666/lib/papers/manifest_updater.rb#L70-L83

**Comment by jasonrclark** [comment]
Good catch @anothermh! If the gem specs are missing a license, we definitely shouldn't be treating it that way.

**Comment by jasonrclark** [comment]
Put a PR up with #21 to address this. If the gemspec doesn't have a license, we should just ignore the "change"
