### ISSUE TITLE
Updating manifest automatically

### ISSUE THREAD

**Issue by codeodor** [newrelic/papers#29]
Is there any reason not to include `Papers::ManifestUpdater.new.update!` in a license validation test?

If not, would you accept a pull request to update the README to include that, or at least a discussion of the pros/cons of doing so?

**Comment by jasonrclark** [comment]
So running the tests would modify the manifest, right? I can see the convenience of that, but with how the updates aren't always seamless it seems like some pros/cons would be the right way to present it. Fire off a PR and we can chat more on the details there!

**Comment by codeodor** [comment]
Ok, thanks. I opened #30 for that purpose.
